// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "pD~W)!))~`SE8~~FjTYG":
            case "polarBear":return img`
111111cffc11111bd1111111111.............
1111bcbddbcccccbccbd1111111.............
111fdddddddddbdddddbffd1111.............
11cdddddddddbddddddddddc111.............
1cddddddddddddddddddcdddc11.............
dbdddddddddddddddddddddbdd1.............
cdddddddddddddddddddddddddd.............
fddddddddddddddddddddddddb1.............
cdddddddddddddddddddddddcc1.............
cddddddddddbddddbdbcccd111..............
cdddddcdddddddddffb1111111..............
cdddddcdddbdddddff1......1..............
cdddddcdddcddddcfc1.....................
cddddbbdddcddddffc1.....................
cddddccffcbdddbffb1.....................
bdddbfffc1bdddcffb1.....................
ddddffffd11dddfffb1...1.................
dddc1fffd11bddfffb1.....................
ddbf1ffffb1fddbffff1....................
bdddbcffff1bddddfffb....................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
