scene.setBackgroundImage(img`
    cccccccccccccccccbbbbbbbbbbbbbcbbbbbbccbbbbbbbbbbddddbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccbbccbddbbbbbbbbbbdddbbbdbbbbbbbbbbbdb
    cccccccccccbbbbbbbbbbbbbbbbbbbccbbccccbbbbbdbbbbdddbbbbbbbbbbbbddbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccbcbbddbbbbbbbbbbdddbbdbbbbbbbbbbbddb
    cbbccccbbbbbbbbbbbbbbbbbbbbbbcccbbccbbbbbddbbbbbbbbbbbbbbbbbbbbdbbbbcbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccbbbdddbbcbbbbbbbdddbbbbbbbbbbbbbbdbb
    cbbbccbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbdddbbddbbbbbbbbbbbbbbbbbbbbccccbbbbbdbbbbbbbccccccccccccccccccccccccccccccccccccccccbbddbbbcbbbbbbbdddbbbbbbbdbbbddbbbb
    bbbbbbbccccccccbbbbbbbbbcccccbbbbbbbbbbddddddddddddbbbbbbbbbbbbbbbbccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccbbbdddbbcbbbbbbbdddbbbbbbbbbbdbbbbbb
    bbbbbbbccccccccbbbbbbbbccccccbbbbbbbbbbddddddbddddbbbcbbbbdbbbbbbcccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbdddddbbbbbbbbbbdbbbdbc
    bbcbbbbbbbccbbcccccccccbbbbccccbbbbcbbbbdddddbdddbbbbbbbbdbbbbbbbcccccccccccbbbbbbbbcbbbccccccccccccccccccccccccccccccccccccbcbbbbbbbbbbbdddbbbdbbbdbbbbbbbbbbb
    bbbbbbbbccccccccccccccccbccccccccccccbbddddddd11ddbbbbbdddbbbbbbccccccccccccccbbbbcccbbbccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbddbbbbbbbbbbbbbbbbbbb
    bbbbbcccccccccccccccccccccccccccccbbbbbddddd1ddddddddbbbbbbcccccccccccccccccccbccbbbbcccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbcbbbcbbbccbbbbddb
    bbbbccccccccccccccccccccccccccbbbbbbbbddddddddddbbddddbbbbcccccccccccccccccccccccbbbccccccccccccccccccccccccccccccccccccccccdddbbbbbbbbddbbbbbbbbcbbbbbbbbbbdbb
    bbbbbcccccccccccccccccccccccccccccbbbddddddddddbbdddddbcbcccccccccccccccccccccccbbdbcccccccccccccccccccccccccccccccccccccccbddbbbbbbbbbdddbbbbbbbbdbbbbbbbbdbbb
    bbbbbccbcccccccccbccccccccccccccbbddddddddddddddddddbcccbcbbbccccccccccccccccccccbdbbbccccccccccccccccccccccccccccccccccccbddbbbbbbbbbbdddbbbbbbddbbbbbdbbbdbbd
    bcccccbcccccccccbbccccccccccccccccbddddddddddddddbbbccccbbbbbbccccccccccccccccccbbbbbbccccccccccccccccccccccccccccccccccccbddbbbbbbbbbddbbbbbbbddbbbbbbdbbbdbdd
    bccccccccccccccccccccccccccccccccccbdbdddddddddbbbbbbbbbbbbbbccccccccccccccccccccbbbbbccccccccccccccccccccccccccccccccccccbdbbbbbbbbbbddbbbbbbddbbbbbbdbbbdbbdb
    bbcccccccccccccccccccccccccccccccccbbbddddddddbbbbbbdddbbbcccccccccccccccccccccccccccbcccbcccccccccccccccccccccccccccccccbbbbcbbbbbbbddbbbbbbddbbbbbbddbbdddbbb
    bccccccccccccccccccccccccccccccccccbbbbbbbddbddbbbbdddbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbccbbbbbbdddbbbbbddbbbbdbbbdbbdddbbb
    bcccccccccccccccccccccccccbbbbccbbbccccbbbddbbbddddddbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbcbbbbbcbddbbbbbdbbbbbbbbbbdddbddbbd
    bcccccccccccccccccccccbbbbbddbbbbbbbbccbbbbbbccbbdddbccccbbccbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbddbbbbbddbbbbbbbbbdddbbbbbbd
    bbbcccccccccccccccccbbbbbbbbdbbbbbbbbbbddbbbbccccbbbccbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbddbbbbbdbbdbbbbbbbbbddbbbbbdd
    ccccccccccccccccccbddddbbbbddbbbbbbbbbbbdbbbbbbccccccbddbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbdbbdbbbbdddd
    ccccccccccccccccbdddddbbbbbbbbbbbbbbbbbbbdbbbccccccccbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbddbbbbdddbb
    ccccccccccccbbbddbbbbbbbbbbbbbbbbbbbbbbbddbbbccccbccccbbbbbcbbbbccccccbbccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbddbbbbbbddbbbd
    ccccccccccbbbbbbbccccbbbbbbbbbbbbbddddddddbbbbbbbbbcccbbbbbcbbbbccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbdbbdddbbbbdd
    ccccccfccbbbccccccccbbbbbbbbbbbbbbbbbbddddbbbbbbcccccccbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcbcbbbbbbddbb
    ccccccccbbbbbbbccccbbbbbbbbbbbbbbbbcbbbdddbbbbccccccccbbbbddbbcccbbbbbbbccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbdddd
    cccccbbbddbbbbbbccbbbbbbbbbccbbbbbbccbbddddbbbccccccccbbbbbbbbbbddddbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbb
    ccbbbbdddddbbbbbbbbbbbbbbbccbbbbbbbccbddddbbbbccccccbcccbbbbbbdddddbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cbbbbbbbdddddddbbbbbbbbbbbccbbbbbbcccbdddbbbbbbbbbcccccccbcccbddbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cbbccccbddddddddbbbbbbbbbccccccccccbbdddbbbbbbbbbbccccccccccccbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccbbddddddbbbbbbbbbbccccccccccbbbbbbbdbbbbbbbbcccccccccccbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    bccccccbbddbbbbbbcccccbcccccccccccbbbbbddbbbcbbbbbbcccccccccccbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccbbbbbbbbbbcccccccccccccccccbbbddddbbbcbbbbbbcccccccccccccbbbbbbbbccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccbbbccbbbbbbccbbbbccccccccccbdddddbbbbcbbbbbccccccccccccccccbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccbbbbbbbbbbbbbbbbbcbccccccccbbdddddbbbbbbccccccccccccccccccccbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccbbdddddbbbbbbbbbccccccccccccbbddbbddbbccccccccccccccccccccccccccbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccbbdddddbbbbbbbbbbbcccccccccbbbddbbbbbcccccbbcccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbcccccccc
    bbbbbddddbbbbbbbbbbbbccccccccbbbbbbbbbcccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbccbccccccccc
    bbbbbbddbbbbbbbbbbbbbccccccccbbbddbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    bbbbbbbbbbcbbbbddddbbbccccccbbbbddbccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccbbccccccccccccccccccccccccccccccccccccccccccccccccccc
    bbccbbbbbbbbbbdddddbbccccccbbdddbbcccccccccccccccccccccccccccccccccccccccccccccccccbcbbcccccccbcbcbbbbbbbbbbbbccccccccccccccbbbbccccccccccccccccccccccccccccccc
    ccccccbbbbbbbddddddbcccccccbddbbcccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccbccbbccccccccccccccbddbccbcbbbcccccbcccccccccccccccccc
    ccccccccbbbbbddddddbbcccccbbdbbcccccccccccccccccccccccccccccccccccccccccccccbbbccccccccccbbbbbbbccccccccccccccccccccccccccccbbbbbbbcbbbccccbbcccccccccccccccccc
    ccccccccccbbdddddbbbbbbbbbbddbbccccccbbcccccccccccccccccccccccccccccccbbccccbccccbcccbbbbbbbbbbbbbbbbbcccccccccccccccccccccbbbbbbbbccccbcccccbbcccccccccccccccc
    ccccccccccbbddbbbbbbbbbbbbbbbbbcbbbccbbcccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbcccccbbbbbbbbccccccccccccccccccccbdddbbbccccbbcccccccccccccccccccccc
    cccccccccbbbddbbbbbbdbbbbbcccccccbccbccccccccccccccccccccccccccccccccccccccccbbbcccccccccccccccccccccbbccccccccccccccccccccccbbbbbbbccccccccccccccccccccccccccc
    ccccccccbbbbbbdbbbdbbbdbbcccccccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccbbcccccccccccccbbbccccccccccc
    ccccccccbbbbbbddbddbbbdbcccccccccccccccccbbbcbcccccccccccccccccccccccccccccccbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccbbbbbbbbbbbbbbbbcccccccccccccccccbbbbbbcccccccccccccccccccccccccbbbbbbddbcccccccccccccccccccccccccccccccccccbbcccccccccccccccccccccccccccccccccccccbbccb
    cccccccbbbbbbbbbbbbbdbccccccccccccccbbbbbbbbbcccbccccccccccccccccccbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbb
    ccccccccccbbbbbbbbbbbcccccccccccccbbbbbbbbbbbccbbcccbcccccccccccbccccccccccccccccccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbb
    cccccccccccbbbbbbbbbcccccccccccbbbbbbbbcbbbcccbbbbbbbcccccccccccccccccccccbbbcccccccccbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbb
    cccccccccccbbbbbbbbccccccccccbbbbbbbbbbbbbccccbbbbcccccccccccccccccccccbccccbbbcccccbcbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbc
    ccccccccbbbbbbbbbbbcccccccccbbdbbbbbbbbbbcccccbbbccccccbcbbcccccccbbbccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccbbbbbbbccccccccccbbbbbbbbbbbbbbbccccccccccccbbbbbbcccccccbccccbccccccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccbbbbbbbccccccbbbbbbbbbbbbbbbbbbbcccccccccccbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    bbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbcccccccccbbbbcccccccbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    bbbcccccbbbbbbbbbbbbbbbbbbbbbbbbdbbdbbbbbdbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    bbbcbcccbdbbbbbbbbbbbbbbbbddbbbddbbbbbbbddbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccbbbbbbbbbbbbbbbbbbccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddd11
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbd11ddd
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbdddbddddd
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbcccbbcccbbbbdddddddd1d
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbddddddddddddb1dd
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbddbbddbbddddddddbddddddddd
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddddbdddbbdbbbdbbbbddddddddd
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdddbbdddbbbbbbbbbbdddddddddd
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbdbddbbbbbbbbbbbdddddbdddd
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbbbbbbbbbbbbccbbbbbbbbdddddbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbcbccbbbbbbbbddbc
    bcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbdbbbbbbbbbbddbbbbccbbbcccbbbbbddbbb
    bccccccccccccccccccccccccccccccccccbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbcbbbcccbbccccbdbbddbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbcbbbdbbbbbbbbbbbbcccbbbbccbbbbddbbbdb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddbbbccbbbbbbbddbbdbbbbbbbbbbbcbbbbdddbbbdb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbdbbbbbbbcbbbbbbbbbbbcbbcbbbbbbbbbbbddbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcbbbbbbbbbbbbcccccbcbbbbdbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbccbbbbbbbbbcccccbbccbbccbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbcbbbbbbbbbbbbbbcccbbbbccbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccbbbbbbbbcbbbbbbbcbbbcbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccbbccbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbdbbbdbbbbbccccbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbddddbbbbcbbcbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbdddbbbdbbbbbcbbbcbcccccbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbccbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdbbbbbbbbbddbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbdbbbbbbdddddbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbdbdddbbdddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbddbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbcbcbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbdbbbdddbbbbbbbcbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbcbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbccbbbbcbdbcbbbbbbcbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcbbbcbbbbbbbbcbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccddbbddbbbbbbbbbbbbbbbbbbccbccbbbccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbb
    ccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbbdddbbbbbbbbbbbbbbbbcccbbccbbbbbbbbbbbcbbbbbcbbbbbcbbbbbbbbbbbbcbbbbbbbbbbbb
    cccbddbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbddbbddbbdbbbbbccbdbbbbcccbbbbbbbcbbbbbdbccbdbbbbbbbcccbbbbbbbbbbbbbbbbbbbbbbcbb
    cccbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccbdbbdbbbdbbbbbbbbcccbbbbbbbbcbbcbbbccbbbbccbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbdbbdbbbbccbbbbbbbbbbbbbbbbcbdbcccbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbddddddbbbbbbbbbbbbbbcbbbbbbbbbbbccbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdddddbbbbbbbbbbbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbcbbcbbbbbbbbbbcbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbdddbbbcbbbbbbbbbbbbbbbbbbbbbbccbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdddbbbcbddbbbbbbbbbbbbbbbbbbbbbbbbccbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccbbccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbbbbbbbbbbbdbbbbbbbbbbbbbbbbcbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    cccccccccccccbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbdbbbbbbbbbbbbbbcbbbbbbccbbbcbbbbbbbdbbbbbcbbbbbdbcbdbbbbbbdbb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcbbbbbbbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbcbbdbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccbdbddbbdbbbbbbbbbbbbbcccbbbcbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbdddddddbccbbbbddbbbbcbbbccbbccbcbdbbbbbdbcbbbbbbbbbbdbbbbbbbdbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbdbbbbccbbbbbbbbccbbbbcbbbcbbbbbbbbbbbbcbdbbbbbbbbbbbbbbbbbbbbb
    bcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbdbbbbbbbbbbbcbccbbbbccbbbbccbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbbbbb
    bccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbdbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddbbbbbbbbbbbbcbbbbbbbbdbbbbbbcbbbbbbbbbbbbdbbbbbbbbbbdbbbbbbbddbbb
    bccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbb
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddbbbbbbbbbbddddbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbbbbb
    ccccccccccccccccccccccccccbbcccccccccccccccccccccccccccccbcccccccccccccccccccccccccccccccccbbbbbbbbddbbbddddbbbbbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbdbbbddbbbbbb
    cccccccccccccccccccccccccbbbcccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccbdbbbbbbddbbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbdbbbbbbbbbbbb
    ccccccccccccccccccccccccbbccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccbbbbbbbddbbbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbdbbbbbbbdbbbbbbbbbbbb
    ccccccccccccccccccccccccbbcccccccccccccccccccccccccccccccccccbbbbbccccbbbcccccbbcccccccbbbbbbbbddbbbddbbddbbbbbdbbbbbbbbbbbbbbbbbbbbddbbbbbbbbbdbbbdddbbbbbbbbb
    `)
let Isbjørnemor = sprites.create(assets.image`polarBear`, SpriteKind.Player)
Isbjørnemor.setPosition(0, 0)
let Ivalo = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
